name: A workflow for my Hello World file
on: push

jobs:
  build:
    strategy:
      matrix:
        node_version: 
          - 15
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        architecture:
          - x64
          - x86
          # - arm64
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - run: npm install
      - run: npm test
      # - uses: ./action-a
      #   with:
      #     MY_NAME: "Shah Rukh Khan"